// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0M35oK63gipQPqQTAULgaxKNOkJ0rba8',
    appId: '1:770190759368:web:1aca5a007d4b371887dcfd',
    messagingSenderId: '770190759368',
    projectId: 'chatappproject-5351e',
    authDomain: 'chatappproject-5351e.firebaseapp.com',
    storageBucket: 'chatappproject-5351e.appspot.com',
    measurementId: 'G-Z66RXQ094G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PO1s7f5lH25pEJFM8yPpHjfst6jQJQI',
    appId: '1:770190759368:android:edb6bf617e7f830687dcfd',
    messagingSenderId: '770190759368',
    projectId: 'chatappproject-5351e',
    storageBucket: 'chatappproject-5351e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmUBUzIjX-fma80qEB9S8LuTyT1ru9Nw',
    appId: '1:770190759368:ios:9e6bccc58ddfbbfa87dcfd',
    messagingSenderId: '770190759368',
    projectId: 'chatappproject-5351e',
    storageBucket: 'chatappproject-5351e.appspot.com',
    iosClientId: '770190759368-h80jpvo6t59jfuv8dpt077vbl4i5r3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmUBUzIjX-fma80qEB9S8LuTyT1ru9Nw',
    appId: '1:770190759368:ios:9e6bccc58ddfbbfa87dcfd',
    messagingSenderId: '770190759368',
    projectId: 'chatappproject-5351e',
    storageBucket: 'chatappproject-5351e.appspot.com',
    iosClientId: '770190759368-h80jpvo6t59jfuv8dpt077vbl4i5r3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappProject',
  );
}
